import { execFileSync } from "node:child_process";
import { writeFile } from "node:fs/promises";

const output = new URL("../src/release.ts", import.meta.url);

let release = {
  tag: "development",
  isoName: "tailboot.iso",
  upstreamUrl: "",
};

if (process.env.WORKERS_CI === "1") {
  const tag = execFileSync(
    "git",
    ["tag", "--points-at", "HEAD", "--list", "v*", "--sort=-version:refname"],
    { encoding: "utf8" },
  )
    .trim()
    .split("\n")[0];
  if (!tag) throw new Error("The checked-out commit has no Tailboot release tag.");

  const isoName = `tailboot-${tag}-amd64.iso`;
  release = {
    tag,
    isoName,
    upstreamUrl: `https://github.com/ShoeBoom/tailboot/releases/download/${tag}/${isoName}`,
  };
}

await writeFile(
  output,
  `// Generated by scripts/prepare-release.ts.\nexport const release = ${JSON.stringify(release, null, 2)} as const;\n`,
);
